# Generated by Django 2.2.11 on 2020-10-31 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0002_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Articles',
        ),
    ]
