# Generated by Django 2.2.11 on 2020-10-31 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0004_auto_20201031_2019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='date',
            new_name='a_date',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='description',
            new_name='a_description',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='title',
            new_name='a_title',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='p_description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_img',
            new_name='p_product_img',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='p_title',
        ),
    ]
