# Generated by Django 2.2.11 on 2020-11-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0007_contactus_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(auto_created=True, max_length=10, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('mobile', models.IntegerField(null=True)),
                ('designation', models.CharField(max_length=15)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('p_product_img', models.ImageField(upload_to='profile_images')),
            ],
        ),
    ]
