# Generated by Django 2.2.11 on 2020-11-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0009_auto_20201108_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourteam',
            name='emp_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
